### ISSUE TITLE
Homepage - Misalignment of History Section

### ISSUE THREAD

**Issue by unknown009d** [joy-dey/DIrectChat#7]
## Description
The History section on the homepage is not aligned properly. The text and images in this section seem to be skewed to the right, whereas they should be centered.

## Steps to Reproduce
1. Go to the homepage.
1. Resize screen below width: 767px.
1. Scroll down to the History section.

## Screenshots
![Screenshot 2024-04-03 020436](https://github.com/joy-dey/DIrectChat/assets/60551363/b93abbf7-cc91-4a08-b476-453cb091a472)

## Environment
- Browser: Microsoft Edge (Version 123.0.2420.65)
- OS: Windows 11
- Device: Desktop 

## Possible Solution
Changing the css selector for #no-history width fixes the problem and aligns it in the center.
```css
@media (max-width: 767px)
body main #history #no-history {
    width: 100%;
}
```
